version: "3"
services:
    web:
        build: .
        ports:
            - "8080:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            SA_PASSWORD: "Marine7815@@"
            ACCEPT_EULA: "Y"
           # MSSQL_DB: "master"
           # MSSQL_USER: "dbuser"
           # MSSQL_PASSWORD: "Marine7815@@"
        ports: 
            - "1433:1433"
